export let data = {
  songs: [
    {
      _id: '1',
      title: 'emulator',
      artists: ['1'],
      length: 140,
      release_date: '2021-06-29',
    },
    {
      _id: '2',
      title: 'Várnék',
      artists: ['1', '5'],
      length: 187,
      release_date: '2022-07-07',
    },
    {
      _id: '3',
      title: 'Pullup',
      artists: ['1', '4'],
      length: 137,
      release_date: '2022-05-20',
    },
    {
      _id: '4',
      title: 'Du hast',
      artists: ['2'],
      length: '235',
      release_date: '1997-08-22',
    },
    {
      _id: '5',
      title: 'Deutschland',
      artists: ['2'],
      length: '322',
      release_date: '2019-05-17',
    },
    {
      _id: '6',
      title: 'Black Star',
      artists: ['3'],
      length: '247',
      release_date: '1995-03-13',
    },
    {
      _id: '7',
      title: 'Morning Bell',
      artists: ['3'],
      length: '275',
      release_date: '2000-10-02',
    },
    {
      _id: '8',
      title: 'Kukásautó',
      artists: ['4'],
      length: '195',
      release_date: '2021-12-02',
    },
    {
      _id: '9',
      title: 'Rét',
      artists: ['1', '4'],
      length: '264',
      release_date: '2020-11-04',
    },
    {
      _id: '10',
      title: 'Minden',
      artists: ['5'],
      length: '198',
      release_date: '2020-04-04',
    },
  ],
  artists: [
    {
      _id: '1',
      name: 'Azahriah',
      nationality: 'Hungarian',
      monthly_listeners: 710_869,
    },
    {
      _id: '2',
      name: 'Rammstein',
      nationality: 'German',
      monthly_listeners: 10_566_869,
    },
    {
      _id: '3',
      name: 'Radiohead',
      nationality: 'English',
      monthly_listeners: 24_128_674,
    },
    {
      _id: '4',
      name: 'Desh',
      nationality: 'Hungarian',
      monthly_listeners: 617_870,
    },
    {
      _id: '5',
      name: 'Dzsúdló',
      nationality: 'Hungarian',
      monthly_listeners: 336_914,
    },
  ],
};
